name: 不是我干的
markdown: redcarpet
#highlighter: pygments
redcarpet:
  extensions: [fenced_code_blocks]
  render_options:
author: yanyiwu
author_email: wuyanyi09@gmail.com
safe: false
url: http://yanyiwu.com
